### ISSUE TITLE
Disposing a runtime.

### ISSUE THREAD

**Issue by mbostock** [observablehq/runtime#147]
There should be a convenient way to delete an entire module or runtime.

**Comment by mbostock** [comment]
Ah. So last time I looked at this, I was thinking of getting all a runtime’s modules (*runtime*._modules), then getting each module’s variables, and calling *variable*.delete. But, modules do not retain references to all of their variables; they only retain references to named variables in *module*._scope. Therefore, I think what we want is to just kill computation at the runtime level, say by causing runtime._compute to throw an error.

**Comment by jashkenas** [comment]
Yes, if we could stop all computation of the runtime, just by killing the main timer ... and then rely on JavaScript to garbage collect everything, that would be ideal.

But I worry about cells with side effects that may have started timers (or other asynchronous events) of their own. Perhaps `runtime.dispose()` could trigger the invalidation promise for every variable — to allow them to responsibly clean themselves up?

**Comment by mbostock** [comment]
Fixed in #162.
