### ISSUE TITLE
Cells that depend on views or mutables cannot be cleanly imported.

### ISSUE THREAD

**Issue by mbostock** [observablehq/runtime#151]
Given [document A](https://observablehq.com/d/bc24298cd70a4c0a):

```js
mutable foo = "foo"
```
```js
mutable_foo_reference = mutable foo
```

And [document B](https://observablehq.com/d/d97ab598251791a1):

```js
import {mutable_foo_reference} from "bc24298cd70a4c0a"
```
```js
mutable_foo_reference
```

We expect the imported `mutable_foo_reference` in document B to equal `"foo"`. However, we instead see a RuntimeError: mutable_foo_reference could not be resolved.

This can be avoided by explicitly importing either `mutable foo` or `foo`, but this additional import should not be necessary.

**Comment by jashkenas** [comment]
I spent some time trying to chase this down yesterday evening, and added a runtime test that I thought should have demonstrated the issue ... but it passes:

https://github.com/observablehq/runtime/commit/9019bfef749255b5ae14d8dad8dfc2d91f88bad9

Something is causing the evaluation of an indirectly imported mutable reference to fail to attempt to evaluate.
