### ISSUE TITLE
4.0.0 broken?

### ISSUE THREAD

**Issue by mbostock** [observablehq/runtime#155]
Unverified report: https://talk.observablehq.com/t/svg-download-on-notebook-but-not-with-runtime/1862/2?u=mike

**Comment by bryangingechen** [comment]
See this block: https://bl.ocks.org/bryangingechen/9040daac97a1f4f31bd15f64a6b16ed0

**Comment by mbostock** [comment]
You need to load the provided ES module bundle rather than using unpkg’s experimental module feature.

```js
import {Runtime, Inspector} from "https://cdn.jsdelivr.net/npm/@observablehq/runtime@4/dist/runtime.js";
```
