### ISSUE TITLE
Example of parsing a cell and evaluating it in the runtime?

### ISSUE THREAD

**Issue by tangert** [observablehq/runtime#166]
I'm currently trying to figure out how to take a parsed cell input and evaluate it in the runtime. Right now all I see is that a parsed cell returns an object, but I'm unsure of how to take this parsed output and convert it into the `module0.variable().define("a", 1)` kind of syntax that modules use. Any help is appreciated!

**Comment by jashkenas** [comment]
Hi @tangert, 

I'm afraid that you can’t quite close the loop just yet — in between the **parser** and the **runtime**, there’s a smaller piece, the **compiler**, that transforms valid, parsed, Observable JavaScript into JavaScript. And we have not yet open sourced it.

**Comment by mkotelnikov** [comment]
Hi @tangert,
You can find an example of code compilation here:
https://observablehq.com/@kotelnikov/observablehq-notebooks-building-and-compiling
Best regards,
Mikhail

**Comment by tangert** [comment]
Hi @mkotelnikov, fantastic! This will be so useful. I wanted to use observable as the backend for a visual programming tool so now it’s looking like a reality :)
