### ISSUE TITLE
`this` not passed to a function cell

### ISSUE THREAD

**Issue by buckle2000** [observablehq/runtime#200]
Let's say we have the two cells below in order to cache a vega-lite chart. However, functions in Observable don't follow the javascript convention; the `this` value of an arrow function is lost between cells.

```js
// cell one
vega = async (spec, datasets, opts) => { // don't change `this`
  // `this` is undefined, maybe because Observable set `this` to the previous value anyway
  const el = this ? this : await vegaEmbed(spec, {
        renderer: 'svg',
        ...opts
      })
  const view = el.value
  for (const name of Object.keys(datasets)) {
    view.data(name, datasets[name])
  }
  return el
}
```

```js
// cell two
viewof view = vega({
  data: {name: 'data'},
  mark: 'line',
  autosize: 'fit-y',
  encoding: {
    x: {field: 'i'},
    y: {field: 'datum'},
  }
}, {data})
```

Also, this is another solution to #119

**Comment by buckle2000** [comment]
@mbostock this might interest you.

**Comment by mbostock** [comment]
Right, it’s not possible to assume the `this` for a function that is called by another cell. You could have multiple levels of function calling that make the `this` ambiguous.

If you want this functionality, you can pass `this` as an argument to your Vega function:

```
vega(spec, options, this)
```

And then you could reference it like so:

```
vega = async (spec, datasets, opts, that) => {
  …
}
```

In general, however, we no longer recommend using `this` for caching the previous values of cells, and it’s likely we will deprecate this feature in the future. Instead we recommend using side-effect cells where one cell mutates a value returned by another cell, say by calling view.data.

**Comment by mbostock** [comment]
Here’s an example of what I mean:

https://observablehq.com/@domoritz/vega-lite-demo-with-streaming-data

**Comment by buckle2000** [comment]
But what if I have several charts; do I have to use equal number of side effect cells? There should be a function that can encapsulate caching/updating.

**Comment by mbostock** [comment]
Yes, I think you’d have one cell for each chart, and an additional cell for each side-effect. If you want to share a notebook I’d be happy to take a look and see if I can think of a more elegant solution.
