### ISSUE TITLE
cross-domain problem

### ISSUE THREAD

**Issue by eatgrass** [observablehq/runtime#213]
check the official example, https://codepen.io/jashkenas/pen/gzZXPG
`Access to script at 'https://api.observablehq.com/d/e8186dc6a68b5179.js?key=65c8f0576a197717' from origin 'https://cdpn.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by jashkenas** [comment]
I've fixed the CodePen example, which was out of date. It should be working again properly now.

Thanks for reporting!
