### ISSUE TITLE
Is there a way not to show the data?

### ISSUE THREAD

**Issue by eyaleizenberg** [observablehq/runtime#231]
I am just starting out with Observablehq so sorry for the noob question. I started out locally modifying this example: https://observablehq.com/@d3/force-directed-graph

My question is, is there a way for me to hide the data part below the graph?

<img width="1908" alt="Screen Shot 2020-02-09 at 16 29 09" src="https://user-images.githubusercontent.com/1061345/74104077-eedf3700-4b59-11ea-8397-e5c44aecbee4.png">

**Comment by mbostock** [comment]
Try this snippet from the README:

```js
const runtime = new Runtime();
const main = runtime.module(define, name => {
  if (name === "chart") {
    return new Inspector(document.body);
  }
});
```

You can display multiple cells this way too, but you’ll need to give each of them a container element.

```js
const runtime = new Runtime();
const main = runtime.module(define, name => {
  if (name === "chart" || name === "legend") {
    return new Inspector(document.querySelector(`#${name}`));
  }
});
```
