### ISSUE TITLE
Re-export d3-require

### ISSUE THREAD

**Issue by GordonSmith** [observablehq/runtime#247]
When writing additional libraries for the runtime which also use d3-require to lazy load dependencies (in UMD mode), the different instances tend to interfere with each other.

If the runtime (and stdlib?) re-exported d3-require then my additional library could use that version and avail of the shared cache + global define.

**Comment by GordonSmith** [comment]
Actually it might be better if we could supply a "primed" require into the runtime / library (so that we could provide a custom resolver etc.)?

**Comment by mbostock** [comment]
You can do that by passing a *resolve* function the [Library constructor](https://github.com/observablehq/stdlib#Library) or by changing the *require* passed to the [Runtime constructor](https://github.com/observablehq/runtime#Runtime).

**Comment by GordonSmith** [comment]
I can see the Library resolve option:  https://github.com/observablehq/stdlib/blob/master/src/library.js#L18-L19

But I don't see anyway to pass a require into the runtime:  https://github.com/observablehq/runtime/blob/master/src/runtime.js#L14-L30

Or am I missing something?

**Comment by asg017** [comment]
@GordonSmith from the [docs](https://github.com/observablehq/runtime#Runtime):


> Or to define a new builtin, or override an existing one:
 > const runtime = new Runtime(Object.assign(new Library, {color: "red"}));

So if you have your own `myRequire` function, you could do something like so:

```javascript
const myRequire = function(){/* whatever your require is */}
const runtime = new Runtime(Object.assign(new Library, {require: myRequire}));
```

This would override the default `require` builtin from the default Observable stdlib with your own `myRequire` implementation. 

Then, with `runtime`, you can define modules with `runtime.module`, and any reference to `require` would use your `myRequire` implementation. 

Keep in mind, your `myRequire` function may need to be wrapped in a function (#195) to work properly. You can see this being used in the [stdlib source](https://github.com/observablehq/stdlib/blob/master/src/library.js#L21-L34), all the builtin cells that are functions (require, html, resolve, etc.) are wrapped in [`constant()`](https://github.com/observablehq/stdlib/blob/master/src/constant.js). So your may need to define your `myRequire` like so:

```javascript
function myRequire() {
  return function() {
    // your implementation
  }
}

const runtime = new Runtime(Object.assign(new Library, {require: myRequire}));
```

**Comment by mbostock** [comment]
See the [custom-library](https://github.com/observablehq/examples/tree/main/custom-library) and [standalone](https://github.com/observablehq/examples/tree/main/standalone) examples for how to override the standard library and provide your own require function. Alternatively, if you want to extract the require used by the runtime, you can say:

```js
const library = new Library();
const require = library.require();
const runtime = new Runtime(library);
```
