### ISSUE TITLE
Cell calculation time profiling

### ISSUE THREAD

**Issue by edeboursetty** [observablehq/runtime#311]
Some calculations take a long time I think it could help sometimes to add calculation timings for each variable.

Maybe as `variable._timings = { start_time: ..., end_time: ...}` and then have `observer.fulfilled(value, timings)`, and `observer.rejected(value, timings)`. 

I'd be happy to do it if you guys think it's a good idea.

**Comment by mbostock** [comment]
Thank you for the suggestion. We don’t currently plan on incorporating profiling directly into the runtime.
