### ISSUE TITLE
check if object is a promise instead of just awaiting it.

### ISSUE THREAD

**Issue by Kreijstal** [observablehq/runtime#343]
I wanted to use @masala/parser which uses objects that have .then methods, they are however NOT promises. which means they break on observable.

Example: `({ then: (_) => _(3) })` shouldn't be awaited since it isn't a promise..

**Comment by mbostock** [comment]
The behavior is the same as Promise.resolve, so yes, we do await all thenables and not just literal promises. You can read about the specification here: https://promisesaplus.com/
