### ISSUE TITLE
Observable using the file:// protocol

### ISSUE THREAD

**Issue by harrylojames** [observablehq/runtime#354]
Hi, 

My aim is to share a html document containing observable which can be loaded in chrome using the file:// protocol. Is it feasible for observable to be made to run over the file protocol? 

For context, it follows from this discussion I had [here on the Quarto github](https://github.com/quarto-dev/quarto-cli/discussions/5680). 

Apologies if this is a question that your documentation already answers. "Observable is only accessible over HTTPS and only encrypted HTTPS and websockets (WSS) are used for data transmission. Our commercial certificate is signed by Cloudflare, and we only allow TLS 1.2 and higher for HTTPS connections." - https://observablehq.com/resources/security

Many thanks!

Harry

**Comment by mbostock** [comment]
The Observable Runtime is just a JavaScript library, so you can use it wherever you like. I’m not aware of any file protocol restriction, and I’m not familiar with Quarto’s OJS runtime so I can’t comment on how it works. I read this comment in the linked thread, but I don’t know what features it is referring to, so I can’t speculate as to why they are saying the HTTP/HTTPS protocol is required.

> But because of features in the observablejs runtime which we have no control over, documents that use OJS need to run on the http:// or https:// protocol; they simply don't work on the file:// protocol. That's not something we can fix.
